
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.20.0.  DO NOT EDIT!
//*************************************************************************************

using Grpc.Core;
using System.Threading.Tasks;
using XTC.FMP.MOD.Assloud.LIB.Proto;

namespace XTC.FMP.MOD.Assloud.App.Service
{
    /// <summary>
    /// Content基类
    /// </summary>
    public class ContentServiceBase : LIB.Proto.Content.ContentBase
    {
    

        public override async Task<ContentListResponse> Match(ContentMatchRequest _request, ServerCallContext _context)
        {
            return await Task.Run(() => new ContentListResponse {
                    Status = new LIB.Proto.Status() { Code = -1, Message = "Not Implemented" },
            });
        }

    }
}

