org_name: XTC
module_name: Assloud
generate:
  active: true
  database_driver: mongodb
  debug: false
  unity_solution: true
publish:
  active: true
  environment: develop
  repository: grpc://nps.meex.cloud:28000
deploy:
  active: true
  environment: develop
  repository: grpc://nps.meex.cloud:28000
  agent_port: 28001
