
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using System.Threading.Tasks;
using XTC.FMP.LIB.MVCS;

namespace XTC.FMP.MOD.Assloud.LIB.Bridge
{
    /// <summary>
    /// Bundle的视图桥接层（协议部分）
    /// 处理UI的事件
    /// </summary>
    public interface IBundleViewProtoBridge : View.Facade.Bridge
    {

        /// <summary>
        /// 处理Create的提交
        /// </summary>
        Task<Error> OnCreateSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理Update的提交
        /// </summary>
        Task<Error> OnUpdateSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理Retrieve的提交
        /// </summary>
        Task<Error> OnRetrieveSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理Delete的提交
        /// </summary>
        Task<Error> OnDeleteSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理List的提交
        /// </summary>
        Task<Error> OnListSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理Search的提交
        /// </summary>
        Task<Error> OnSearchSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理PrepareUploadResource的提交
        /// </summary>
        Task<Error> OnPrepareUploadResourceSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理FlushUploadResource的提交
        /// </summary>
        Task<Error> OnFlushUploadResourceSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理FetchResources的提交
        /// </summary>
        Task<Error> OnFetchResourcesSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理DeleteResource的提交
        /// </summary>
        Task<Error> OnDeleteResourceSubmit(IDTO _dto, object? _context);


        /// <summary>
        /// 处理Tidy的提交
        /// </summary>
        Task<Error> OnTidySubmit(IDTO _dto, object? _context);


    }
}

