
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.20.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using System.Threading.Tasks;
using XTC.FMP.LIB.MVCS;

namespace XTC.FMP.MOD.Assloud.LIB.Bridge
{
    /// <summary>
    /// Content的视图桥接层（协议部分）
    /// 处理UI的事件
    /// </summary>
    public interface IContentViewProtoBridge : View.Facade.Bridge
    {

        /// <summary>
        /// 处理Match的提交
        /// </summary>
        Task<Error> OnMatchSubmit(IDTO _dto, SynchronizationContext? _context);


    }
}

