
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.Assloud.LIB.Proto;

namespace XTC.FMP.MOD.Assloud.LIB.MVCS
{
    /// <summary>
    /// Bundle控制层基类
    /// </summary>
    public class BundleControllerBase : Controller
    {
        /// <summary>
        /// 带uid参数的构造函数
        /// </summary>
        /// <param name="_uid">实例化后的唯一识别码</param>
        /// <param name="_gid">直系的组的ID</param>
        public BundleControllerBase(string _uid, string _gid) : base(_uid)
        {
            gid_ = _gid;
        }


        /// <summary>
        /// 更新Create的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Create的回复</param>
        public virtual void UpdateProtoCreate(BundleModel.BundleStatus? _status, UuidResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            UuidResponseDTO? dto = new UuidResponseDTO(_response);
            getView()?.RefreshProtoCreate(err, dto, _context);
        }

        /// <summary>
        /// 更新Update的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Update的回复</param>
        public virtual void UpdateProtoUpdate(BundleModel.BundleStatus? _status, UuidResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            UuidResponseDTO? dto = new UuidResponseDTO(_response);
            getView()?.RefreshProtoUpdate(err, dto, _context);
        }

        /// <summary>
        /// 更新Retrieve的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Retrieve的回复</param>
        public virtual void UpdateProtoRetrieve(BundleModel.BundleStatus? _status, BundleRetrieveResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            BundleRetrieveResponseDTO? dto = new BundleRetrieveResponseDTO(_response);
            getView()?.RefreshProtoRetrieve(err, dto, _context);
        }

        /// <summary>
        /// 更新Delete的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Delete的回复</param>
        public virtual void UpdateProtoDelete(BundleModel.BundleStatus? _status, UuidResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            UuidResponseDTO? dto = new UuidResponseDTO(_response);
            getView()?.RefreshProtoDelete(err, dto, _context);
        }

        /// <summary>
        /// 更新List的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">List的回复</param>
        public virtual void UpdateProtoList(BundleModel.BundleStatus? _status, BundleListResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            BundleListResponseDTO? dto = new BundleListResponseDTO(_response);
            getView()?.RefreshProtoList(err, dto, _context);
        }

        /// <summary>
        /// 更新Search的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Search的回复</param>
        public virtual void UpdateProtoSearch(BundleModel.BundleStatus? _status, BundleListResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            BundleListResponseDTO? dto = new BundleListResponseDTO(_response);
            getView()?.RefreshProtoSearch(err, dto, _context);
        }

        /// <summary>
        /// 更新PrepareUploadResource的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">PrepareUploadResource的回复</param>
        public virtual void UpdateProtoPrepareUploadResource(BundleModel.BundleStatus? _status, PrepareUploadResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            PrepareUploadResponseDTO? dto = new PrepareUploadResponseDTO(_response);
            getView()?.RefreshProtoPrepareUploadResource(err, dto, _context);
        }

        /// <summary>
        /// 更新FlushUploadResource的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">FlushUploadResource的回复</param>
        public virtual void UpdateProtoFlushUploadResource(BundleModel.BundleStatus? _status, FlushUploadResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            FlushUploadResponseDTO? dto = new FlushUploadResponseDTO(_response);
            getView()?.RefreshProtoFlushUploadResource(err, dto, _context);
        }

        /// <summary>
        /// 更新FetchResources的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">FetchResources的回复</param>
        public virtual void UpdateProtoFetchResources(BundleModel.BundleStatus? _status, BundleFetchResourcesResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            BundleFetchResourcesResponseDTO? dto = new BundleFetchResourcesResponseDTO(_response);
            getView()?.RefreshProtoFetchResources(err, dto, _context);
        }

        /// <summary>
        /// 更新DeleteResource的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">DeleteResource的回复</param>
        public virtual void UpdateProtoDeleteResource(BundleModel.BundleStatus? _status, DeleteUploadResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            DeleteUploadResponseDTO? dto = new DeleteUploadResponseDTO(_response);
            getView()?.RefreshProtoDeleteResource(err, dto, _context);
        }

        /// <summary>
        /// 更新Tidy的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Tidy的回复</param>
        public virtual void UpdateProtoTidy(BundleModel.BundleStatus? _status, UuidResponse _response, object? _context)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            UuidResponseDTO? dto = new UuidResponseDTO(_response);
            getView()?.RefreshProtoTidy(err, dto, _context);
        }


        /// <summary>
        /// 获取直系视图层
        /// </summary>
        /// <returns>视图层</returns>
        protected BundleView? getView()
        {
            if(null == view_)
                view_ = findView(BundleView.NAME + "." + gid_) as BundleView;
            return view_;
        }

        /// <summary>
        /// 直系的MVCS的四个组件的组的ID
        /// </summary>
        protected string gid_ = "";

        /// <summary>
        /// 直系视图层
        /// </summary>
        private BundleView? view_;
    }
}
