
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.12.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.Assloud.LIB.Proto;

namespace XTC.FMP.MOD.Assloud.LIB.MVCS
{
    /// <summary>
    /// Content控制层基类
    /// </summary>
    public class ContentControllerBase : Controller
    {
        /// <summary>
        /// 带uid参数的构造函数
        /// </summary>
        /// <param name="_uid">实例化后的唯一识别码</param>
        /// <param name="_gid">直系的组的ID</param>
        public ContentControllerBase(string _uid, string _gid) : base(_uid)
        {
            gid_ = _gid;
        }


        /// <summary>
        /// 更新Match的数据
        /// </summary>
        /// <param name="_status">直系状态</param>
        /// <param name="_response">Match的回复</param>
        public virtual void UpdateProtoMatch(ContentModel.ContentStatus? _status, ContentListResponse _response)
        {
            Error err = new Error(_response.Status.Code, _response.Status.Message);
            ContentListResponseDTO? dto = new ContentListResponseDTO(_response);
            getView()?.RefreshProtoMatch(err, dto);
        }


        /// <summary>
        /// 获取直系视图层
        /// </summary>
        /// <returns>视图层</returns>
        protected ContentView? getView()
        {
            if(null == view_)
                view_ = findView(ContentView.NAME + "." + gid_) as ContentView;
            return view_;
        }

        /// <summary>
        /// 直系的MVCS的四个组件的组的ID
        /// </summary>
        protected string gid_ = "";

        /// <summary>
        /// 直系视图层
        /// </summary>
        private ContentView? view_;
    }
}
