
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.12.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using System.Threading.Tasks;
using Grpc.Net.Client;
using XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.Assloud.LIB.Proto;

namespace XTC.FMP.MOD.Assloud.LIB.MVCS
{
    /// <summary>
    /// Content服务层基类
    /// </summary>
    public class ContentServiceBase : Service
    {
        public ContentServiceMock mock { get; set; } = new ContentServiceMock();
    
        /// <summary>
        /// 带uid参数的构造函数
        /// </summary>
        /// <param name="_uid">实例化后的唯一识别码</param>
        /// <param name="_gid">直系的组的ID</param>
        public ContentServiceBase(string _uid, string _gid) : base(_uid)
        {
            gid_ = _gid;
        }

        /// <summary>
        /// 注入GRPC通道
        /// </summary>
        /// <param name="_channel">GRPC通道</param>
        public void InjectGrpcChannel(GrpcChannel? _channel)
        {
            grpcChannel_ = _channel;
        }


        /// <summary>
        /// 调用Match
        /// </summary>
        /// <param name="_request">Match的请求</param>
        /// <returns>错误</returns>
        public virtual async Task<Error> CallMatch(ContentMatchRequest? _request, SynchronizationContext? _context)
        {
            getLogger()?.Trace("Call Match ...");
            if (null == _request)
            {
                return Error.NewNullErr("parameter:_request is null");
            }

            ContentListResponse? response = null;
            if (null != mock.CallMatchDelegate)
            {
                getLogger()?.Trace("use mock ...");
                response = await mock.CallMatchDelegate(_request);
            }
            else
            {
                var client = getGrpcClient();
                if (null == client)
                {
                    return await Task.FromResult(Error.NewNullErr("client is null"));
                }
                response = await client.MatchAsync(_request);
            }

            getModel()?.UpdateProtoMatch(response, _context);
            return Error.OK;
        }


        /// <summary>
        /// 获取直系数据层
        /// </summary>
        /// <returns>数据层</returns>
        protected ContentModel? getModel()
        {
            if(null == model_)
                model_ = findModel(ContentModel.NAME + "." + gid_) as ContentModel;
            return model_;
        }

        /// <summary>
        /// 获取GRPC客户端
        /// </summary>
        /// <returns>GRPC客户端</returns>
        protected Content.ContentClient? getGrpcClient()
        {
            if (null == grpcChannel_)
                return null;

            if(null == clientContent_)
            {
                clientContent_ = new Content.ContentClient(grpcChannel_);
            }
            return clientContent_;
        }

        /// <summary>
        /// 直系的MVCS的四个组件的组的ID
        /// </summary>
        protected string gid_ = "";

        /// <summary>
        /// GRPC客户端
        /// </summary>
        protected Content.ContentClient? clientContent_;

        /// <summary>
        /// GRPC通道
        /// </summary>
        protected GrpcChannel? grpcChannel_;

        /// <summary>
        /// 直系数据层
        /// </summary>
        private ContentModel? model_;
    }

}
