
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.12.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.MOD.Assloud.LIB.Proto;

namespace XTC.FMP.MOD.Assloud.LIB.MVCS
{
    /// <summary>
    /// Content服务模拟类
    /// </summary>
    public class ContentServiceMock
    {


        public System.Func<ContentMatchRequest, Task<ContentListResponse>>? CallMatchDelegate { get; set; } = null;

    }
}
