
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.20.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.Assloud.LIB.Proto;
using XTC.FMP.MOD.Assloud.LIB.Bridge;

namespace XTC.FMP.MOD.Assloud.LIB.MVCS
{

    public class ContentMatchRequestDTO : IDTO
    {
        public ContentMatchRequestDTO(ContentMatchRequest _value)
        {
            Value = _value;    
        }
        public readonly ContentMatchRequest Value;
    }



    public class ContentListResponseDTO : IDTO
    {
        public ContentListResponseDTO(ContentListResponse _value)
        {
            Value = _value;    
        }
        public readonly ContentListResponse Value;
    }



    public class DesignerReadStylesResponseDTO : IDTO
    {
        public DesignerReadStylesResponseDTO(DesignerReadStylesResponse _value)
        {
            Value = _value;    
        }
        public readonly DesignerReadStylesResponse Value;
    }



    public class DesignerWriteStylesRequestDTO : IDTO
    {
        public DesignerWriteStylesRequestDTO(DesignerWriteStylesRequest _value)
        {
            Value = _value;    
        }
        public readonly DesignerWriteStylesRequest Value;
    }



    public class DesignerReadInstancesResponseDTO : IDTO
    {
        public DesignerReadInstancesResponseDTO(DesignerReadInstancesResponse _value)
        {
            Value = _value;    
        }
        public readonly DesignerReadInstancesResponse Value;
    }



    public class DesignerWriteInstancesRequestDTO : IDTO
    {
        public DesignerWriteInstancesRequestDTO(DesignerWriteInstancesRequest _value)
        {
            Value = _value;    
        }
        public readonly DesignerWriteInstancesRequest Value;
    }



    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class MetaEntityDTO : IDTO
    {
        public MetaEntityDTO(MetaEntity _value)
        {
            Value = _value;    
        }
        public readonly MetaEntity Value;
    }



    public class ContentEntityDTO : IDTO
    {
        public ContentEntityDTO(ContentEntity _value)
        {
            Value = _value;    
        }
        public readonly ContentEntity Value;
    }



}
