
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.61.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.Assloud.LIB.Proto;
using XTC.FMP.MOD.Assloud.LIB.Bridge;

namespace XTC.FMP.MOD.Assloud.LIB.MVCS
{

    public class BundleCreateRequestDTO : IDTO
    {
        public BundleCreateRequestDTO(BundleCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly BundleCreateRequest Value;
    }



    public class BundleUpdateRequestDTO : IDTO
    {
        public BundleUpdateRequestDTO(BundleUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly BundleUpdateRequest Value;
    }



    public class BundleRetrieveResponseDTO : IDTO
    {
        public BundleRetrieveResponseDTO(BundleRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly BundleRetrieveResponse Value;
    }



    public class BundleListRequestDTO : IDTO
    {
        public BundleListRequestDTO(BundleListRequest _value)
        {
            Value = _value;    
        }
        public readonly BundleListRequest Value;
    }



    public class BundleListResponseDTO : IDTO
    {
        public BundleListResponseDTO(BundleListResponse _value)
        {
            Value = _value;    
        }
        public readonly BundleListResponse Value;
    }



    public class BundleSearchRequestDTO : IDTO
    {
        public BundleSearchRequestDTO(BundleSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly BundleSearchRequest Value;
    }



    public class BundleFetchResourcesResponseDTO : IDTO
    {
        public BundleFetchResourcesResponseDTO(BundleFetchResourcesResponse _value)
        {
            Value = _value;    
        }
        public readonly BundleFetchResourcesResponse Value;
    }



    public class ContentCreateRequestDTO : IDTO
    {
        public ContentCreateRequestDTO(ContentCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly ContentCreateRequest Value;
    }



    public class ContentUpdateRequestDTO : IDTO
    {
        public ContentUpdateRequestDTO(ContentUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly ContentUpdateRequest Value;
    }



    public class ContentRetrieveResponseDTO : IDTO
    {
        public ContentRetrieveResponseDTO(ContentRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly ContentRetrieveResponse Value;
    }



    public class ContentListRequestDTO : IDTO
    {
        public ContentListRequestDTO(ContentListRequest _value)
        {
            Value = _value;    
        }
        public readonly ContentListRequest Value;
    }



    public class ContentListResponseDTO : IDTO
    {
        public ContentListResponseDTO(ContentListResponse _value)
        {
            Value = _value;    
        }
        public readonly ContentListResponse Value;
    }



    public class ContentSearchRequestDTO : IDTO
    {
        public ContentSearchRequestDTO(ContentSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly ContentSearchRequest Value;
    }



    public class ContentMatchRequestDTO : IDTO
    {
        public ContentMatchRequestDTO(ContentMatchRequest _value)
        {
            Value = _value;    
        }
        public readonly ContentMatchRequest Value;
    }



    public class ContentFetchAttachmentsResponseDTO : IDTO
    {
        public ContentFetchAttachmentsResponseDTO(ContentFetchAttachmentsResponse _value)
        {
            Value = _value;    
        }
        public readonly ContentFetchAttachmentsResponse Value;
    }



    public class DesignerReadStylesResponseDTO : IDTO
    {
        public DesignerReadStylesResponseDTO(DesignerReadStylesResponse _value)
        {
            Value = _value;    
        }
        public readonly DesignerReadStylesResponse Value;
    }



    public class DesignerWriteStylesRequestDTO : IDTO
    {
        public DesignerWriteStylesRequestDTO(DesignerWriteStylesRequest _value)
        {
            Value = _value;    
        }
        public readonly DesignerWriteStylesRequest Value;
    }



    public class DesignerReadInstancesResponseDTO : IDTO
    {
        public DesignerReadInstancesResponseDTO(DesignerReadInstancesResponse _value)
        {
            Value = _value;    
        }
        public readonly DesignerReadInstancesResponse Value;
    }



    public class DesignerWriteInstancesRequestDTO : IDTO
    {
        public DesignerWriteInstancesRequestDTO(DesignerWriteInstancesRequest _value)
        {
            Value = _value;    
        }
        public readonly DesignerWriteInstancesRequest Value;
    }



    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidRequestDTO : IDTO
    {
        public UuidRequestDTO(UuidRequest _value)
        {
            Value = _value;    
        }
        public readonly UuidRequest Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class PrepareUploadRequestDTO : IDTO
    {
        public PrepareUploadRequestDTO(PrepareUploadRequest _value)
        {
            Value = _value;    
        }
        public readonly PrepareUploadRequest Value;
    }



    public class PrepareUploadResponseDTO : IDTO
    {
        public PrepareUploadResponseDTO(PrepareUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly PrepareUploadResponse Value;
    }



    public class FlushUploadRequestDTO : IDTO
    {
        public FlushUploadRequestDTO(FlushUploadRequest _value)
        {
            Value = _value;    
        }
        public readonly FlushUploadRequest Value;
    }



    public class FlushUploadResponseDTO : IDTO
    {
        public FlushUploadResponseDTO(FlushUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly FlushUploadResponse Value;
    }



    public class FileSubEntityDTO : IDTO
    {
        public FileSubEntityDTO(FileSubEntity _value)
        {
            Value = _value;    
        }
        public readonly FileSubEntity Value;
    }



    public class ContentEntityDTO : IDTO
    {
        public ContentEntityDTO(ContentEntity _value)
        {
            Value = _value;    
        }
        public readonly ContentEntity Value;
    }



    public class BundleEntityDTO : IDTO
    {
        public BundleEntityDTO(BundleEntity _value)
        {
            Value = _value;    
        }
        public readonly BundleEntity Value;
    }



}
