
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.12.0.  DO NOT EDIT!
//*************************************************************************************

using System;
using LibMVCS = XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.Assloud.LIB.Bridge;

namespace XTC.FMP.MOD.Assloud.LIB.Unity
{

    public class ContentUiBridgeBase : IContentUiBridge
    {
        public LibMVCS.Logger logger { get; set; }

        public virtual void Alert(string _code, string _message)
        {
            throw new NotImplementedException();
        }


        public virtual void RefreshMatch(IDTO _dto)
        {
            throw new NotImplementedException();
        }

    }
}
