
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.33.1.  DO NOT EDIT!
//*************************************************************************************

using System;
using System.Threading;
using LibMVCS = XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.Assloud.LIB.Bridge;

namespace XTC.FMP.MOD.Assloud.LIB.Unity
{

    public class ContentUiBridgeBase : IContentUiBridge
    {
        public LibMVCS.Logger logger { get; set; }

        public virtual void Alert(string _code, string _message, object _context)
        {
            throw new NotImplementedException();
        }


        public virtual void RefreshCreate(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshUpdate(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshRetrieve(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshDelete(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshList(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshSearch(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

        public virtual void RefreshMatch(IDTO _dto, object _context)
        {
            throw new NotImplementedException();
        }

    }
}
